service:
  name: odin

plugins:
  - serverless-plugin-epsagon
  - serverless-webpack
  - serverless-cloudformation-resource-counter
  - serverless-stack-output

provider:
  name: aws
  runtime: nodejs8.10
  stage: local
  environment:
    REVISION: ${file(infrastructure/helper.js):revision}
    STAGE: ${self:provider.stage}
    DELETE_STACK_TOPIC:
      Fn::Join:
        - ':'
        - - arn:aws:sns
          - Ref: AWS::Region
          - Ref: AWS::AccountId
          - delete-stack-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Resource: '*'
      Action: '*'

custom:
  epsagon:
    token: ${env:EPSAGON_TOKEN}
    appName: ${self:service.name}-pariveda-serverless-${self:provider.stage}
  odin: ${file(./odin.yml)}
  # output is used by the serverless-stack-output plugin
  output: { file: ./infrastructure/stack-outputs.yml }

functions:
  checkStacks:
    handler: app/check.handler
    events:
      - schedule:
          rate: ${self:custom.odin.dailyRate}
          input:
            staleAfter: ${self:custom.odin.dailyStaleAfter}
            stagesToRetain: ${self:custom.odin.stagesToRetain}
            deleteableStatuses: ${self:custom.odin.deleteableStatuses}
            namesToRetain: ${self:custom.odin.namesToRetain}
      - schedule:
          rate: ${self:custom.odin.hourlyRate}
          input:
            staleAfter: ${self:custom.odin.hourlyStaleAfter}
            stagesToRetain: ${self:custom.odin.stagesToRetain}
            deleteableStatuses: ${self:custom.odin.deleteableStatuses}
            namesToRetain: ${self:custom.odin.namesToRetain}

  deleteStacks:
    handler: app/delete.handler
    events:
      - sns: delete-stack-${opt:stage, self:provider.stage}
    environment:
      EMPTY_ALL_BUCKETS: ${self:custom.odin.emptyAllBuckets}
      BUCKETS_TO_EMPTY: ${self:custom.odin.bucketsToEmpty}

resources:
  Description: Automated service for destroying temporary stacks (retains permanenent stacks)

  Outputs:
    DailySchedule:
      Description: Schedule for daily jobs and maximum stack age in hours before deletion
      Value: ${self:custom.odin.dailyRate} and ${self:custom.odin.dailyStaleAfter}
    HourlySchedule:
      Description: Schedule for hourly jobs and maximum stack age in hours before deletion
      Value: ${self:custom.odin.hourlyRate} and ${self:custom.odin.hourlyStaleAfter}
    StacksToRetain:
      Description: Attributes of stacks that won't be deleted
      Value: 'Names: !${self:custom.odin.namesToRetain} Stages: !${self:custom.odin.stagesToRetain} Statuses: ${self:custom.odin.deleteableStatuses}'

    DeleteStackSNS:
      Description: ARN of the ${opt:stage, self:provider.stage} stage SNS topic for stack deletion
      Value:
        Fn::Join:
          - ':'
          - - arn:aws:sns:us-east-1
            - Ref: AWS::AccountId
            - delete-stack-${opt:stage, self:provider.stage}
      Export:
        Name: odin-${opt:stage, self:provider.stage}-delete-stack-sns
