service:
  name: odin
app: automation

plugins:
  - serverless-plugin-epsagon
  - serverless-webpack
  - serverless-cloudformation-resource-counter
  - serverless-stack-output

provider:
  name: aws
  runtime: nodejs8.10
  region: ${self:custom.config.region}
  stage: ${self:custom.config.stage}
  profile: ${self:custom.config.profile}
  environment:
    REVISION: ${file(infrastructure/helper.js):revision}
    STAGE: ${self:provider.stage}
    DELETE_STACK_TOPIC:
      Fn::Join:
        - ':'
        - - arn:aws:sns:us-east-1
          - Ref: AWS::AccountId
          - delete-stack-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Resource: '*'
      Action: '*'

custom:
  epsagon:
    token: ${self:custom.config.epsagonToken}
    appName: ${self:service.name}-${self:provider.stage}
  odin: ${file(./odin.yml)}
  config: ${file(./infrastructure/configurations.yml)}
  # output is used by the serverless-stack-output plugin
  output: { file: ./infrastructure/stack-outputs.yml }
  properties: ${file(./infrastructure/properties.yml)}

functions:
  checkStacks:
    handler: app/check.handler
    events:
      - schedule:
          rate: ${self:custom.odin.dailyRate}
          input:
            staleAfter: ${self:custom.odin.dailyStaleAfter}
            stagesToRetain: ${self:custom.odin.stagesToRetain}
            deleteableStatuses: ${self:custom.odin.deleteableStatuses}
      - schedule:
          rate: ${self:custom.odin.hourlyRate}
          input:
            staleAfter: ${self:custom.odin.hourlyStaleAfter}
            stagesToRetain: ${self:custom.odin.stagesToRetain}
            deleteableStatuses: ${self:custom.odin.deleteableStatuses}

  deleteStacks:
    handler: app/delete.handler
    events:
      - sns: delete-stack-${opt:stage, self:provider.stage}
    environment:
      EMPTY_ALL_BUCKETS: ${self:custom.odin.emptyAllBuckets}
      BUCKETS_TO_EMPTY: ${self:custom.odin.bucketsToEmpty}

resources:
  Description: Automated service for destroying temporary stacks (retains production, qa, development, and automation stacks)

  Outputs:
    DeleteStackSNS:
      Description: ARN of the ${opt:stage, self:provider.stage} stage SNS topic for stack deletion
      Value:
        Fn::Join:
          - ':'
          - - arn:aws:sns:us-east-1
            - Ref: AWS::AccountId
            - delete-stack-${opt:stage, self:provider.stage}
      Export:
        Name: odin-${opt:stage, self:provider.stage}-delete-stack-sns
