defaultProfile: personal
iopipeToken: ${env:IOPIPE_TOKEN, file(infrastructure/credentials.local.yml):IOPIPE_TOKEN}
logLevel: ${self:custom.properties.logLevel.${self:custom.config.stage}, self:custom.properties.logLevel.default}
profile: ${file(infrastructure/helper.js):profile}
region: us-east-1
revision: ${file(infrastructure/helper.js):revision}
stage: ${file(infrastructure/helper.js):stage}
tags:
  stage: ${self:custom.config.stage}
  revision: ${self:custom.config.revision}
